"""add fsrs_card_json to kc_mastery

Revision ID: 37dca26607ff
Revises: abd6f99fa052
Create Date: 2026-06-13 12:05:21.099707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37dca26607ff'
down_revision: Union[str, Sequence[str], None] = 'abd6f99fa052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kc_mastery', sa.Column('fsrs_card_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kc_mastery', 'fsrs_card_json')
    # ### end Alembic commands ###
