"""Add full database schema

Revision ID: abd6f99fa052
Revises: 4163dbfe589e
Create Date: 2026-06-13 06:24:22.183702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abd6f99fa052'
down_revision: Union[str, Sequence[str], None] = '4163dbfe589e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bkt_priors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('subject', sa.String(length=20), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('knowledge_point', sa.String(length=100), nullable=True),
    sa.Column('question_type', sa.String(length=20), nullable=True),
    sa.Column('p_init', sa.Float(), nullable=True),
    sa.Column('p_transit', sa.Float(), nullable=True),
    sa.Column('p_guess', sa.Float(), nullable=True),
    sa.Column('p_slip', sa.Float(), nullable=True),
    sa.Column('calibrated_from_n', sa.Integer(), server_default='0', nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('effortful_gains',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('struggle_score', sa.Float(), nullable=True),
    sa.Column('retention_delta', sa.Float(), nullable=True),
    sa.Column('effortful_gain', sa.Float(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solve_cache',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kc_id', sa.String(length=100), nullable=True),
    sa.Column('problem_hash', sa.String(length=64), nullable=True),
    sa.Column('solve_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('solvable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_hash')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('role', sa.Enum('student', 'parent', name='userrole'), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('province', sa.String(length=10), server_default='广东', nullable=True),
    sa.Column('invite_code', sa.String(length=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('daily_missions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('mission_type', sa.Enum('review', 'socratic', 'upload', 'knowledge_focus', name='missiontype'), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('interleaved', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('requires_active_recall', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('completed', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'date')
    )
    op.create_table('daily_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('report_text', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'date')
    )
    op.create_table('exams',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('exam_name', sa.String(length=100), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('subject', sa.String(length=20), server_default='math', nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guardian_consents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('guardian_phone', sa.String(length=11), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('consent_version', sa.String(length=20), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interaction_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('knowledge_point', sa.String(length=100), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('paper', 'quick', 'review', 'socratic', name='interactionsource'), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('fsrs_rating', sa.SmallInteger(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('days_since_last', sa.Float(), nullable=True),
    sa.Column('is_interleaved', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kc_mastery',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('knowledge_point', sa.String(length=100), nullable=False),
    sa.Column('p_mastery', sa.Float(), nullable=True),
    sa.Column('p_init', sa.Float(), nullable=False),
    sa.Column('p_transit', sa.Float(), nullable=False),
    sa.Column('p_guess', sa.Float(), nullable=False),
    sa.Column('p_slip', sa.Float(), nullable=False),
    sa.Column('p_recognition', sa.Float(), nullable=True),
    sa.Column('p_recognition_init', sa.Float(), nullable=True),
    sa.Column('long_term_mastery', sa.Float(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('n_attempts', sa.Integer(), server_default='0', nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'knowledge_point')
    )
    op.create_table('learning_patterns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('pattern_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_marked_useful', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mastery_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('knowledge_point', sa.String(length=100), nullable=True),
    sa.Column('long_term_mastery', sa.Float(), nullable=True),
    sa.Column('dominant_error_type', sa.String(length=20), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('snapshot_month', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.Enum('emotion', 'score_drop', 'task_missing', 'time_drop', 'late_night', name='alerttype'), nullable=True),
    sa.Column('alert_level', sa.Enum('notice', 'attention', 'important', name='alertlevel'), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sent_via', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_student',
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'student_id')
    )
    op.create_table('streaks',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('current_streak', sa.Integer(), server_default='0', nullable=True),
    sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=True),
    sa.Column('last_completed_date', sa.Date(), nullable=True),
    sa.Column('escape_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('papers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=20), server_default='math', nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ocr_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('processing', 'done', 'failed', name='paperstatus'), server_default='processing', nullable=True),
    sa.Column('storage_tier', sa.Enum('hot', 'warm', 'cold', 'archived', name='storagetier'), server_default='hot', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wrong_questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=20), server_default='math', nullable=True),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('student_answer', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('knowledge_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_type', sa.Enum('conceptual', 'transfer', 'careless', 'logic_break', 'dontknow', name='errortype'), nullable=True),
    sa.Column('profiler_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fsrs_card_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fsrs_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fsrs_state', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_pages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('plot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diagram_svg', sa.Text(), nullable=True),
    sa.Column('self_check_passed', sa.Boolean(), nullable=True),
    sa.Column('report_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['wrong_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('socratic_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.Enum('deep', 'mixed', 'sprint', name='socraticmode'), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('emotion_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outcome', sa.Enum('success', 'partial', 'failed', 'abandoned', name='socraticoutcome'), nullable=True),
    sa.Column('used_escape_hatch', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['wrong_questions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('socratic_sessions')
    op.drop_table('lesson_pages')
    op.drop_table('wrong_questions')
    op.drop_table('papers')
    op.drop_table('streaks')
    op.drop_table('parent_student')
    op.drop_table('parent_alerts')
    op.drop_table('mastery_snapshots')
    op.drop_table('learning_patterns')
    op.drop_table('kc_mastery')
    op.drop_table('interaction_events')
    op.drop_table('guardian_consents')
    op.drop_table('exams')
    op.drop_table('daily_reports')
    op.drop_table('daily_missions')
    op.drop_table('users')
    op.drop_table('solve_cache')
    op.drop_table('effortful_gains')
    op.drop_table('bkt_priors')
    # ### end Alembic commands ###
