"""add speaking_sessions table

Revision ID: be949dd2c0d0
Revises: d9f542e964bf
Create Date: 2026-06-19 03:20:45.116401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be949dd2c0d0'
down_revision: Union[str, Sequence[str], None] = 'd9f542e964bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaking_sessions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('turns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pronunciation_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overall_progress', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speaking_sessions')
    # ### end Alembic commands ###
